project:
  type: website

website:
  title: "Ocean & Climate Data Challenge"
  navbar:
    left:
      - href: leaderboard.qmd
        text: Home
      - about.qmd
  repo-url: https://github.com/ppr-ocean-ia/dc-tools
  favicon: favicon.ico

format:
  html:
    theme:
      - flatly
    css: styles.css
    toc: true
    echo: false
    page-layout: full



